import type {
  IdealOttoReferenceCase,
  IdealOttoReferenceTolerances,
} from "@/reference/engineering/ideal-otto/types";

export const IDEAL_OTTO_REFERENCE_TOLERANCES:
  IdealOttoReferenceTolerances =
  {
    gasConstantJPerKgK: {
      absolute:
        1e-12,

      relative:
        1e-12,
    },

    gamma: {
      absolute:
        1e-12,

      relative:
        1e-12,
    },

    specificHeatJPerKgK: {
      absolute:
        1e-9,

      relative:
        1e-12,
    },

    temperatureK: {
      absolute:
        1e-6,

      relative:
        1e-10,
    },

    pressurePa: {
      absolute:
        1e-3,

      relative:
        1e-10,
    },

    specificVolumeM3PerKg: {
      absolute:
        1e-10,

      relative:
        1e-10,
    },

    specificEnergyJPerKg: {
      absolute:
        1e-3,

      relative:
        1e-10,
    },

    efficiency: {
      absolute:
        1e-10,

      relative:
        1e-10,
    },
  };

export const reportAppendixBReference:
  IdealOttoReferenceCase =
  {
    id:
      "otto-reference-report-appendix-b",

    label:
      "Report Appendix B — r8, qin 800 kJ/kg",

    basis:
      "report_appendix_b_independent_recalculation",

    sourceIds: [
      "source-mit-otto-cycle",
    ],

    note:
      "High-precision constants independently recalculated from the Appendix B model equations; they are not generated by production functions.",

    input: {
      compressionRatio:
        8,

      initialTemperatureK:
        300,

      initialPressurePa:
        100_000,

      heatInputJPerKg:
        800_000,
    },

    expected: {
      gasProperties: {
        gasConstantJPerKgK:
          287,

        gamma:
          1.4,

        cvJPerKgK:
          717.5000000000001,

        cpJPerKgK:
          1004.5000000000001,
      },

      states: {
        state1: {
          temperatureK:
            300,

          pressurePa:
            100_000,

          specificVolumeM3PerKg:
            0.861,
        },

        state2: {
          temperatureK:
            689.2190129982209,

          pressurePa:
            1_837_917.3679952559,

          specificVolumeM3PerKg:
            0.107625,
        },

        state3: {
          temperatureK:
            1804.2015913954333,

          pressurePa:
            4_811_204.243721155,

          specificVolumeM3PerKg:
            0.107625,
        },

        state4: {
          temperatureK:
            785.3243558445291,

          pressurePa:
            261_774.7852815097,

          specificVolumeM3PerKg:
            0.861,
        },
      },

      energy: {
        heatInputJPerKg:
          800_000,

        heatRejectedJPerKg:
          348_220.2253184497,

        netWorkJPerKg:
          451_779.7746815503,

        thermalEfficiencyFromEnergyBalance:
          0.5647247183519378,

        thermalEfficiencyFromCompressionRatio:
          0.5647247183519379,
      },
    },

    tolerances:
      IDEAL_OTTO_REFERENCE_TOLERANCES,
  };

export const halfHeatInputReference:
  IdealOttoReferenceCase =
  {
    id:
      "otto-reference-r8-half-heat",

    label:
      "Analytic QA — r8, qin 400 kJ/kg",

    basis:
      "analytic_qa_derivation",

    sourceIds: [
      "source-mit-otto-cycle",
    ],

    note:
      "Derived analytic QA case for checking that heat input changes temperatures and work while ideal efficiency remains unchanged at fixed r and gamma.",

    input: {
      compressionRatio:
        8,

      initialTemperatureK:
        300,

      initialPressurePa:
        100_000,

      heatInputJPerKg:
        400_000,
    },

    expected: {
      gasProperties: {
        gasConstantJPerKgK:
          287,

        gamma:
          1.4,

        cvJPerKgK:
          717.5000000000001,

        cpJPerKgK:
          1004.5000000000001,
      },

      states: {
        state1: {
          temperatureK:
            300,

          pressurePa:
            100_000,

          specificVolumeM3PerKg:
            0.861,
        },

        state2: {
          temperatureK:
            689.2190129982209,

          pressurePa:
            1_837_917.3679952559,

          specificVolumeM3PerKg:
            0.107625,
        },

        state3: {
          temperatureK:
            1246.7103021968271,

          pressurePa:
            3_324_560.8058582055,

          specificVolumeM3PerKg:
            0.107625,
        },

        state4: {
          temperatureK:
            542.6621779222645,

          pressurePa:
            180_887.39264075484,

          specificVolumeM3PerKg:
            0.861,
        },
      },

      energy: {
        heatInputJPerKg:
          400_000,

        heatRejectedJPerKg:
          174_110.1126592248,

        netWorkJPerKg:
          225_889.8873407752,

        thermalEfficiencyFromEnergyBalance:
          0.5647247183519379,

        thermalEfficiencyFromCompressionRatio:
          0.5647247183519379,
      },
    },

    tolerances:
      IDEAL_OTTO_REFERENCE_TOLERANCES,
  };

export const higherCompressionRatioReference:
  IdealOttoReferenceCase =
  {
    id:
      "otto-reference-r10",

    label:
      "Analytic QA — r10, qin 800 kJ/kg",

    basis:
      "analytic_qa_derivation",

    sourceIds: [
      "source-mit-otto-cycle",
    ],

    note:
      "Derived analytic QA case for checking compression-ratio sensitivity and ideal-efficiency increase.",

    input: {
      compressionRatio:
        10,

      initialTemperatureK:
        300,

      initialPressurePa:
        100_000,

      heatInputJPerKg:
        800_000,
    },

    expected: {
      gasProperties: {
        gasConstantJPerKgK:
          287,

        gamma:
          1.4,

        cvJPerKgK:
          717.5000000000001,

        cpJPerKgK:
          1004.5000000000001,
      },

      states: {
        state1: {
          temperatureK:
            300,

          pressurePa:
            100_000,

          specificVolumeM3PerKg:
            0.861,
        },

        state2: {
          temperatureK:
            753.5659294528739,

          pressurePa:
            2_511_886.4315095795,

          specificVolumeM3PerKg:
            0.0861,
        },

        state3: {
          temperatureK:
            1868.5485078500863,

          pressurePa:
            6_228_495.026166954,

          specificVolumeM3PerKg:
            0.0861,
        },

        state4: {
          temperatureK:
            743.8825595021572,

          pressurePa:
            247_960.85316738574,

          specificVolumeM3PerKg:
            0.861,
        },
      },

      energy: {
        heatInputJPerKg:
          800_000,

        heatRejectedJPerKg:
          318_485.7364427978,

        netWorkJPerKg:
          481_514.2635572022,

        thermalEfficiencyFromEnergyBalance:
          0.6018928294465027,

        thermalEfficiencyFromCompressionRatio:
          0.6018928294465027,
      },
    },

    tolerances:
      IDEAL_OTTO_REFERENCE_TOLERANCES,
  };

export const alternateInitialStateReference:
  IdealOttoReferenceCase =
  {
    id:
      "otto-reference-r6-alternate-state",

    label:
      "Analytic QA — alternate initial state",

    basis:
      "analytic_qa_derivation",

    sourceIds: [
      "source-mit-otto-cycle",
    ],

    note:
      "Derived analytic QA case using a different initial temperature, pressure, compression ratio, and heat input to reduce overfitting to the Appendix B example.",

    input: {
      compressionRatio:
        6,

      initialTemperatureK:
        320,

      initialPressurePa:
        120_000,

      heatInputJPerKg:
        600_000,
    },

    expected: {
      gasProperties: {
        gasConstantJPerKgK:
          287,

        gamma:
          1.4,

        cvJPerKgK:
          717.5000000000001,

        cpJPerKgK:
          1004.5000000000001,
      },

      states: {
        state1: {
          temperatureK:
            320,

          pressurePa:
            120_000,

          specificVolumeM3PerKg:
            0.7653333333333333,
        },

        state2: {
          temperatureK:
            655.25520354535,

          pressurePa:
            1_474_324.2079770376,

          specificVolumeM3PerKg:
            0.12755555555555556,
        },

        state3: {
          temperatureK:
            1491.4921373432594,

          pressurePa:
            3_355_857.309022334,

          specificVolumeM3PerKg:
            0.12755555555555556,
        },

        state4: {
          temperatureK:
            728.3841186875989,

          pressurePa:
            273_144.0445078496,

          specificVolumeM3PerKg:
            0.7653333333333333,
        },
      },

      energy: {
        heatInputJPerKg:
          600_000,

        heatRejectedJPerKg:
          293_015.60515835223,

        netWorkJPerKg:
          306_984.39484164777,

        thermalEfficiencyFromEnergyBalance:
          0.511640658069413,

        thermalEfficiencyFromCompressionRatio:
          0.5116406580694131,
      },
    },

    tolerances:
      IDEAL_OTTO_REFERENCE_TOLERANCES,
  };

export const idealOttoReferenceCases:
  readonly IdealOttoReferenceCase[] =
  [
    reportAppendixBReference,

    halfHeatInputReference,

    higherCompressionRatioReference,

    alternateInitialStateReference,
  ];