import type {
  BeamStaticsReferenceCase,
} from "@/reference/engineering/beam-statics/types";

/**
 * IMPORTANT
 * ---------
 * These expected values are independent verification
 * references.
 *
 * They must never be regenerated from
 * beamStaticsModel or another production function.
 *
 * Source basis:
 * Mechivra Comprehensive Project Report v1.0,
 * Appendix A.
 */

export const centeredPointLoadReference: BeamStaticsReferenceCase =
  {
    id:
      "reference-beam-statics-centered-point-load",

    title:
      "Centered point load on a simply supported beam",

    independentMethod:
      "Independent static-equilibrium reference recorded from Appendix A1 of the Mechivra project report. Expected values are stored explicitly and are not generated by production model code.",

    sourceIds: [
      "source-mit-beam-displacements",
    ],

    input: {
      spanM: 4,
      pointLoadN: 10_000,
      loadPositionM: 2,
    },

    expected: {
      leftReactionN: 5_000,
      rightReactionN: 5_000,

      maximumMomentNm:
        10_000,

      maximumMomentPositionM:
        2,

      shear: {
        leftOfLoadN: 5_000,
        rightOfLoadN: -5_000,
      },

      momentPoints: [
        {
          xM: 0,
          expectedMomentNm: 0,
        },
        {
          xM: 2,
          expectedMomentNm:
            10_000,
        },
        {
          xM: 4,
          expectedMomentNm: 0,
        },
      ],
    },

    tolerance: {
      absolute: 1e-9,
      relative: 1e-12,
    },
  };

export const eccentricPointLoadReference: BeamStaticsReferenceCase =
  {
    id:
      "reference-beam-statics-eccentric-point-load",

    title:
      "Eccentric point load one metre from the left support",

    independentMethod:
      "Independent static-equilibrium reference recorded from Appendix A2 of the Mechivra project report. Expected values are stored explicitly and are not generated by production model code.",

    sourceIds: [
      "source-mit-beam-displacements",
    ],

    input: {
      spanM: 4,
      pointLoadN: 10_000,
      loadPositionM: 1,
    },

    expected: {
      leftReactionN: 7_500,
      rightReactionN: 2_500,

      maximumMomentNm:
        7_500,

      maximumMomentPositionM:
        1,
    },

    tolerance: {
      absolute: 1e-9,
      relative: 1e-12,
    },
  };

export const beamStaticsReferenceCases: readonly BeamStaticsReferenceCase[] =
  [
    centeredPointLoadReference,
    eccentricPointLoadReference,
  ];